server:
  port: 8801
spring:
  application:
    name: cloud-stream-privider
  rabbitmq:
    host: 192.168.0.110
    port: 5672
    username: admin
    password: 123
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        output:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔
    prefer-ip-address: true #访问的路径变为IP地址

